name: CI/CD

on:
  push:
    branches:
      - main

env:
  SECRETS_MANAGER_ACCESS_TOKEN: ${{ secrets.SECRETS_MANAGER_ACCESS_TOKEN }}
  PATCH_VERSION: ${{ github.run_number }}

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      src: ${{ steps.filter.outputs.src }}
      test: ${{ steps.filter.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'Cargo.toml'
              - '.github/workflows/ci-cd.yaml'
            test:
              - 'test_data/**'
              - 'tests/**'
              - '.github/workflows/ci-only.yaml'
  ci:
    needs: changes
    runs-on: ubuntu-latest

    timeout-minutes: 10

    if: ${{ needs.changes.outputs.src == 'true' || needs.changes.outputs.test == 'true' }}
    steps:
      - name: Checkout cp-config
        uses: actions/checkout@v3
        with:
          repository: 'simpleg-eu/cp-config'
          path: './cp-config'
      - name: Run cp-config in background
        run: |
          cd cp-config
          docker-compose up -d
          cd ../
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace placeholder version
        run: |
          sed -i 's/5123.0.0/${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ env.PATCH_VERSION }}/' ./Cargo.toml
      - name: Run tests
        run: |
          mkdir bin
          cd bin
          curl -LO https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip
          unzip bws-x86_64-unknown-linux-gnu-0.3.0.zip
          chmod +x bws
          export PATH=$PATH:$PWD
          cd ../
          cargo test --all-features
  cd:
    needs: ci
    if: ${{ needs.changes.outputs.src == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace placeholder version
        run: |
          sed -i 's/5123.0.0/${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ env.PATCH_VERSION }}/' ./Cargo.toml
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PATCH_VERSION: ${{ github.run_number }}
        with:
          tag_name: v${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ env.PATCH_VERSION }}
          release_name: v${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ env.PATCH_VERSION }}
          draft: false
          prerelease: false
      - name: Publish crate to crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish --allow-dirty