name: CI only

on:
  push:
    branches-ignore:
      - main
  pull_request:

env:
  SECRETS_MANAGER_ACCESS_TOKEN: ${{ secrets.SECRETS_MANAGER_ACCESS_TOKEN }}

jobs:
  ci-only:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout cp-config
        uses: actions/checkout@v3
        with:
          repository: 'simpleg-eu/cp-config'
          sparse-checkout: 'docker-compose.yaml'
      - name: Run cp-config in background
        run: |
          docker-compose up -d
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          mkdir bin
          cd bin
          curl -LO https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip
          unzip bws-x86_64-unknown-linux-gnu-0.3.0.zip
          chmod +x bws
          export PATH=$PATH:$PWD
          cd ../
          cargo test --all-features